---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kos-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kos-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kos-demo
    spec:
      serviceAccountName: kos-demo
      containers:
      - image: matthaeusheer/kos-demo-backend:{{ .Values.image.version }}
        name: kos-demo-container
        securityContext:
          runAsUser: 1000
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /liveness
            port: 8000
            scheme: HTTP
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: svc-kos-demo
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: kos-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kos-demo
spec:
  ingressClassName: nginx
  rules:
  - host: demobackend.k8s.kos.cheap 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-kos-demo
            port:
              number: 8000
  tls:
  - hosts:
    - demo.kos.cheap

